# Generated by Django 5.2.11 on 2026-02-06 17:08

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFilename)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show, 1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.getFilename)),
                ('carat', models.IntegerField(choices=[(18, '18 Carat'), (22, '22 Carat'), (24, '24 Carat')])),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight of jewel in grams', max_digits=10)),
                ('wastage', models.DecimalField(decimal_places=2, help_text='Wastage percentage', max_digits=5)),
                ('price_without_wastage', models.DecimalField(decimal_places=2, help_text='Price without wastage', max_digits=12)),
                ('price_add_wastage', models.DecimalField(decimal_places=2, help_text='Price including wastage', max_digits=12)),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catagory')),
            ],
        ),
    ]
