# Generated by Django 5.2.11 on 2026-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carat',
            field=models.IntegerField(blank=True, choices=[(18, '18 Carat'), (22, '22 Carat'), (24, '24 Carat'), (925, '925 Sterling Silver'), ('FL', 'FL'), ('VVS1', 'VVS1 Carat'), ('VVS2', 'VVS2 Carat '), ('VS1', 'VS1 Carat'), ('VS2', 'VS2 Carat'), ('SI1', 'SI1 Carat'), ('SI2', 'SI2 Carat')]),
        ),
    ]
