# Generated by Django 5.2.11 on 2026-02-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_carat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carat',
            field=models.IntegerField(blank=True, choices=[(18, '18 Carat'), (22, '22 Carat'), (24, '24 Carat'), (925, '925 Sterling Silver'), (1.15, '1.15 Carat'), (1.5, '1.50 Carat'), (1.85, '1.85 Carat'), (2.25, '2.25 Carat'), (3.05, '3.05 Carat'), (3.5, '3.50 Carat'), (4.2, '4.20 Carat'), (4.65, '4.65 Carat'), (5.5, '5.50 Carat'), (6.25, '6.25 Carat'), (6.85, '6.85 Carat'), (8.2, '8.20 Carat'), (12.5, '12.50 Carat'), (15.0, '15.00 Carat')], null=True),
        ),
    ]
