# Generated by Django 5.2.11 on 2026-02-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_carat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carat',
            field=models.IntegerField(blank=True, choices=[(18, '18 Carat'), (22, '22 Carat'), (24, '24 Carat'), (925, '925 Sterling Silver'), (1.15, 'VVS2 Carat')], null=True),
        ),
    ]
