# Generated by Django 5.2.11 on 2026-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_metalrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalrate',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='metal',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
