# Generated by Django 5.2.11 on 2026-02-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_metalrate_change_alter_metalrate_metal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetalRate',
        ),
    ]
