# Generated by Django 5.2.11 on 2026-02-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
