# Generated by Django 5.2.11 on 2026-02-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
