# Generated by Django 5.2.11 on 2026-02-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewel_type', models.CharField(max_length=100)),
                ('karat', models.IntegerField()),
                ('design_type', models.CharField(max_length=100)),
                ('stone_included', models.BooleanField()),
                ('gold_given_weight', models.FloatField()),
                ('final_weight', models.FloatField()),
                ('predicted_wastage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
