# Generated by Django 5.2.11 on 2026-03-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_order_number_order_ordered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
