# Generated by Django 5.2.11 on 2026-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_order_order_number_remove_order_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_mode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
