# Generated by Django 5.2.11 on 2026-03-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_mode',
            field=models.CharField(default='Cash On Delivery', max_length=50),
        ),
    ]
