# Generated by Django 5.2.11 on 2026-03-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_orderitem_address_orderitem_city_orderitem_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='state',
        ),
    ]
