# Generated by Django 5.2.11 on 2026-03-14 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_orderitem_address_remove_orderitem_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketrate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='marketrate',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
